#! /bin/bash

# Check for GUPPI_DIR
if test "${GUPPI_DIR}zz" = zz; then
    export GUPPI_DIR=/data1/demorest/guppi_daq
fi
echo "Using GUPPI_DIR=$GUPPI_DIR"

# Locations of stuff
opt64=/opt/64bit
python=$opt64/bin/python
guppi_dir=${GUPPI_DIR}
guppi_bin_dir=$guppi_dir/bin
guppi_python_dir=$guppi_dir/python

# Important vars
export PYTHONPATH=$opt64/lib/python:$opt64/lib/python/site-packages:$opt64/presto/lib/python
export LD_LIBRARY_PATH=$opt64/lib:$opt64/pgplot:$opt64/presto/lib

# Run to make sure status shmem exists
$guppi_bin_dir/check_guppi_status > /dev/null

# Run to make sure databuf exists
$guppi_bin_dir/check_guppi_databuf -c 2>/dev/null > /dev/null

# Fill params in
$python $guppi_python_dir/guppi_set_params_parspec.py $1 $2 $3 $4 $5

# Start data flow
$guppi_bin_dir/test_net_thread -p 4001 -s 2056 10.17.0.10 &

# Start monitor
$python $guppi_python_dir/guppi_simple_monitor.py

# When that exits, kill data flow
pkill -INT test_net_thread
