# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_possem', [dirname(__file__)])
        except ImportError:
            import _possem
            return _possem
        if fp is not None:
            try:
                _mod = imp.load_module('_possem', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _possem = swig_import_helper()
    del swig_import_helper
else:
    import _possem
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


O_CREAT = _possem.O_CREAT
O_EXCL = _possem.O_EXCL

def sem_open(*args):
  return _possem.sem_open(*args)
sem_open = _possem.sem_open

def sem_post(*args):
  return _possem.sem_post(*args)
sem_post = _possem.sem_post

def sem_wait(*args):
  return _possem.sem_wait(*args)
sem_wait = _possem.sem_wait

def sem_close(*args):
  return _possem.sem_close(*args)
sem_close = _possem.sem_close


