#ifndef __machinefits_read_cmd__
#define __machinefits_read_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -v: switch on verbose program operation */
  char verboseP;
  /***** -q: recalculate quantization parameters continuously (every row) */
  char quantizeP;
  /***** -bandx: use 'bandX' file labeling */
  char bandxP;
  /***** -data: path to directory containing MACHINEFITS input */
  char dataP;
  char* data;
  int dataC;
  /***** -ifmeta: location of IF .fits metadata */
  char ifmetaP;
  char* ifmeta;
  int ifmetaC;
  /***** -huge: try a really huge value or `inf' or `-inf' */
  char hugeP;
  double huge;
  int hugeC;
  /***** -freq: set or override band center frequency (Hz) */
  char freqP;
  double freq;
  int freqC;
  /***** -ra: set or override right ascension */
  char raP;
  double ra;
  int raC;
  /***** -dec: set or override declination */
  char decP;
  double dec;
  int decC;
  /***** -startchan: channel to start with in psrfits output */
  char startchanP;
  int startchan;
  int startchanC;
  /***** -endchan: last channel to keep in psrfits output */
  char endchanP;
  int endchan;
  int endchanC;
  /***** -spectra: number of spectra to pack in each subint (row) of PSRFITS output */
  char spectraP;
  int spectra;
  int spectraC;
  /***** -rows: number of subints (rows) to pack in each PSRFITS output file */
  char rowsP;
  int rows;
  int rowsC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *tool;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

