%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                             %
%   Center for Astronomy Signal Processing and Electronics Research           %
%   http://casper.berkeley.edu                                                %      
%   Copyright (C) 2011    Hong Chen                                           %
%                                                                             %
%   This program is free software; you can redistribute it and/or modify      %
%   it under the terms of the GNU General Public License as published by      %
%   the Free Software Foundation; either version 2 of the License, or         %
%   (at your option) any later version.                                       %
%                                                                             %
%   This program is distributed in the hope that it will be useful,           %
%   but WITHOUT ANY WARRANTY; without even the implied warranty of            %
%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             %
%   GNU General Public License for more details.                              %
%                                                                             %
%   You should have received a copy of the GNU General Public License along   %
%   with this program; if not, write to the Free Software Foundation, Inc.,   %
%   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.               %
%                                                                             %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% n_inputs: Number of parallel input streams
% n_bits:   Bit width of input/output data
% bin_pt:   Position of binary point of input/output data
% diff_length: Differentiation length
% latency:  Add/Sub latency
function parallel_differentiator_init_xblock(blk, varargin)

defaults = {'n_inputs', 4, ...
            'n_bits', 18, ...
            'bin_pt', 16, ...
            'diff_length', 2, ...
            'latency', 2};
            

n_inputs = get_var('n_inputs', 'defaults', defaults, varargin{:});
n_bits = get_var('n_bits', 'defaults', defaults, varargin{:});
bin_pt = get_var('bin_pt', 'defaults', defaults, varargin{:});
diff_length = get_var('diff_length', 'defaults', defaults, varargin{:});
latency = get_var('latency', 'defaults', defaults, varargin{:});


if n_inputs ==1
    sync_in = xInport('sync_in');
    inport = xInport('in');
    sync_out = xOutport('sync_out');
    outport = xOutport('out');
    
    d_in = xSignal('d_in');
    delay_blk = xBlock(struct('source', 'Delay', 'name', 'Delay'), ...
                          struct('latency', diff_length), ...
                          {inport}, ...
                          {d_in});
                      
    sub_out = xSignal('sub_out');
    sub_blk = xBlock(struct('source','AddSub', 'name', 'sub_blk1'), ...
                         struct('mode', 'Subtraction', 'latency', latency, 'precision', 'User Defined', ...
                                'arith_type', 'Signed  (2''s comp)', ...
                                'n_bits', n_bits, 'bin_pt', bin_pt, ...
                                'quantization', 'Truncate',...
                                'overflow', 'Wrap', ...
                                'use_behavioral_HDL', 'on'), ...
                                {inport, d_in}, ...
                                {sub_out});   
    outport.bind(sub_out);
    
    sync_delay = xBlock(struct('source', 'Delay', 'name', 'sync_delay'), ...
                              struct('latency', latency), ...
                              {sync_in}, ...
                              {sync_out});
    
elseif diff_length <= n_inputs
    
    sync_in = xInport('sync_in');
    sync_out = xOutport('sync_out');
    inports = cell(1,n_inputs);
    outports = cell(1,n_inputs);
    for i =1:n_inputs
        inports{i} = xInport(['in',num2str(i)]);
        outports{i} = xOutport(['out',num2str(i)]);
    end
    
    delay_blks = cell(1,diff_length);
    d_ins = cell(1,diff_length);
    for i =1:diff_length
        d_ins{i} = xSignal(['d_in',num2str(n_inputs-i+1)]);
        delay_blks{i} = xBlock(struct('source', 'Delay', 'name', ['Delay',num2str(n_inputs-i+1)]), ...
                              struct('latency', 1), ...
                              {inports{n_inputs-i+1}}, ...
                              {d_ins{i}});
    end
    
    sub_blks = cell(1,n_inputs);
    for i =1:diff_length
        sub_blks{i} = xBlock(struct('source','AddSub', 'name', ['sub_blk', num2str(i)]), ...
                         struct('mode', 'Subtraction', 'latency', latency, 'precision', 'User Defined', ...
                                'arith_type', 'Signed  (2''s comp)', ...
                                'n_bits', n_bits, 'bin_pt', bin_pt, ...
                                'quantization', 'Truncate',...
                                'overflow', 'Wrap', ...
                                'use_behavioral_HDL', 'on'), ...
                                {inports{i}, d_ins{i}}, ...
                                {outports{i}}); 
    end
    
    for i = diff_length+1: n_inputs
            sub_blks{i} = xBlock(struct('source','AddSub', 'name',[ 'sub_blk',num2str(i)]), ...
                     struct('mode', 'Subtraction', 'latency', latency, 'precision', 'User Defined', ...
                            'arith_type', 'Signed  (2''s comp)', ...
                            'n_bits', n_bits, 'bin_pt', bin_pt, ...
                            'quantization', 'Truncate',...
                            'overflow', 'Wrap', ...
                            'use_behavioral_HDL', 'on'), ...
                            {inports{i}, inports{i-diff_length}}, ...
                            {outports{i}}); 
    end
    
    sync_delay = xBlock(struct('source', 'Delay', 'name', 'sync_delay'), ...
                              struct('latency', latency), ...
                              {sync_in}, ...
                              {sync_out});
                          
else
    sync_in = xInport('sync_in');
    sync_out = xOutport('sync_out');
    inports = cell(1,n_inputs);
    outports = cell(1,n_inputs);
    for i =1:n_inputs
        inports{i} = xInport(['in',num2str(i)]);
        outports{i} = xOutport(['out',num2str(i)]);
    end
    
    delay_blks = cell(1,n_inputs);
    d_ins = cell(1,n_inputs);
    for i =1:n_inputs
        d_ins{i} = xSignal(['d_in',num2str(mod(i-1-diff_length,n_inputs)+1)]);
        delay_blks{i} = xBlock(struct('source', 'Delay', 'name', ['Delay',num2str(mod(i-1-diff_length,n_inputs)+1)]), ...
                              struct('latency', ceil((diff_length-i+1)/n_inputs)), ...
                              {inports{mod(i-1-diff_length,n_inputs)+1}}, ...
                              {d_ins{i}});
    end
    
    sub_blks = cell(1,n_inputs);
    for i =1:n_inputs
        sub_blks{i} = xBlock(struct('source','AddSub', 'name', ['sub_blk', num2str(i)]), ...
                         struct('mode', 'Subtraction', 'latency', latency, 'precision', 'User Defined', ...
                                'arith_type', 'Signed  (2''s comp)', ...
                                'n_bits', n_bits, 'bin_pt', bin_pt, ...
                                'quantization', 'Truncate',...
                                'overflow', 'Wrap', ...
                                'use_behavioral_HDL', 'on'), ...
                                {inports{i}, d_ins{i}}, ...
                                {outports{i}}); 
    end
    
    sync_delay = xBlock(struct('source', 'Delay', 'name', 'sync_delay'), ...
                              struct('latency', latency), ...
                              {sync_in}, ...
                              {sync_out});
                          
end




if ~isempty(blk)
    if ~strcmp(blk(1), '/')
        fmtstr=sprintf('Differentiation length = %d\nBitwidth = %d bin_pt=%d', diff_length, n_bits, bin_pt);
        set_param(blk,'AttributesFormatString', fmtstr);
        clean_blocks(blk);
    end
end

end