function spead_packet(spead_msw, spead_lsw, pkt_bits, fifo_latency)
% function spead_packet(blk,vararg)
% Default to spead_msw:64
%            spead_lsw:40
%            pkt_bits:12
%            fifo_latency:4
% This is a generated function based on subsystem:
%     SPEAD_packetizer/spead_packet
% Though there are limitations about the generated script, 
% the main purpose of this utility is to make learning
% Sysgen Script easier.
% 
% To test it, run the following commands from MATLAB console:
% cfg.source = str2func('spead_packet');
% cfg.toplevel = 'SPEAD_packetizer/spead_packet';
% args = {my_spead_msw, my_spead_lsw, my_pkt_bits, my_fifo_latency};
% xBlock(cfg, args);
% 
% You can edit spead_packet.m to debug your script.
% 
% You can also replace the MaskInitialization code with the 
% following commands so the subsystem will be generated 
% according to the values of mask parameters.
% cfg.source = str2func('spead_packet');
% cfg.toplevel = gcb;
% args = {spead_msw, spead_lsw, pkt_bits, fifo_latency};
% xBlock(cfg, args);
% 
% To configure the xBlock call in debug mode, in which mode,
% autolayout will be performed every time a block is added,
% run the following commands:
% cfg.source = str2func('spead_packet');
% cfg.toplevel = gcb;
% cfg.debug = 1;
% args = {spead_msw, spead_lsw, pkt_bits, fifo_latency};
% xBlock(cfg, args);
% 
% To make the xBlock smart so it won't re-generate the
% subsystem if neither the arguments nor the scripts are
% changes, use as the following:
% cfg.source = str2func('spead_packet');
% cfg.toplevel = gcb;
% cfg.depend = {'spead_packet'};
% args = {spead_msw, spead_lsw, pkt_bits, fifo_latency};
% xBlock(cfg, args);
% 
% See also xBlock, xInport, xOutport, xSignal, xlsub2script.
% defaults = {'spead_msw',64,'spead_lsw',40,'pkt_bits', 12, 'fifo_latency', 4};
% filter_coeffs = get_var('filter_coeffs','defaults', defaults, varargin{:});

%% inports
xlsub2_data_in = xInport('data_in');
xlsub2_pkt_rdy = xInport('pkt_rdy');
xlsub2_heap_cnt = xInport('heap_cnt');
xlsub2_heap_size = xInport('heap_size');
xlsub2_heap_offset = xInport('heap_offset');
xlsub2_heap_stamp = xInport('heap_stamp');
xlsub2_last_pps = xInport('last_pps');
xlsub2_status_bits = xInport('status_bits');

%% outports
xlsub2_data_out = xOutport('data_out');
xlsub2_data_valid1 = xOutport('data_valid1');
xlsub2_eof = xOutport('eof');
xlsub2_ack_out = xOutport('ack_out');

%% diagram

% block: SPEAD_packetizer/spead_packet/Assert1
xlsub2_Assert1_out1 = xSignal;
xlsub2_Assert1 = xBlock(struct('source', 'Assert', 'name', 'Assert1'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 40, ...
                               'bin_pt', 0), ...
                        {xlsub2_heap_cnt}, ...
                        {xlsub2_Assert1_out1});

% block: SPEAD_packetizer/spead_packet/Assert2
xlsub2_Assert2_out1 = xSignal;
xlsub2_Assert2 = xBlock(struct('source', 'Assert', 'name', 'Assert2'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 40, ...
                               'bin_pt', 0), ...
                        {xlsub2_heap_size}, ...
                        {xlsub2_Assert2_out1});

% block: SPEAD_packetizer/spead_packet/Assert3
xlsub2_Assert3_out1 = xSignal;
xlsub2_Assert3 = xBlock(struct('source', 'Assert', 'name', 'Assert3'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 40, ...
                               'bin_pt', 0), ...
                        {xlsub2_heap_offset}, ...
                        {xlsub2_Assert3_out1});

% block: SPEAD_packetizer/spead_packet/Assert4
xlsub2_Assert4_out1 = xSignal;
xlsub2_Assert4 = xBlock(struct('source', 'Assert', 'name', 'Assert4'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 40, ...
                               'bin_pt', 0), ...
                        {xlsub2_heap_stamp}, ...
                        {xlsub2_Assert4_out1});

% block: SPEAD_packetizer/spead_packet/Assert5
xlsub2_Assert5_out1 = xSignal;
xlsub2_Assert5 = xBlock(struct('source', 'Assert', 'name', 'Assert5'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 40, ...
                               'bin_pt', 0), ...
                        {xlsub2_last_pps}, ...
                        {xlsub2_Assert5_out1});

% block: SPEAD_packetizer/spead_packet/Assert6
xlsub2_Assert6_out1 = xSignal;
xlsub2_Assert6 = xBlock(struct('source', 'Assert', 'name', 'Assert6'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 32, ...
                               'bin_pt', 0), ...
                        {xlsub2_data_in}, ...
                        {xlsub2_Assert6_out1});

% block: SPEAD_packetizer/spead_packet/Assert7
xlsub2_Assert7_out1 = xSignal;
xlsub2_Assert7 = xBlock(struct('source', 'Assert', 'name', 'Assert7'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Unsigned', ...
                               'n_bits', 40, ...
                               'bin_pt', 0), ...
                        {xlsub2_status_bits}, ...
                        {xlsub2_Assert7_out1});

% block: SPEAD_packetizer/spead_packet/Assert8
xlsub2_Assert8_out1 = xSignal;
xlsub2_Assert8 = xBlock(struct('source', 'Assert', 'name', 'Assert8'), ...
                        struct('assert_type', 'on', ...
                               'arith_type', 'Boolean', ...
                               'n_bits', 64, ...
                               'bin_pt', 0), ...
                        {xlsub2_pkt_rdy}, ...
                        {xlsub2_Assert8_out1});

% block: SPEAD_packetizer/spead_packet/Concat
xlsub2_Constant3_out1 = xSignal;
xlsub2_Constant4_out1 = xSignal;
xlsub2_Constant5_out1 = xSignal;
xlsub2_Constant6_out1 = xSignal;
xlsub2_Constant7_out1 = xSignal;
xlsub2_Constant8_out1 = xSignal;
xlsub2_Concat_out1 = xSignal;
xlsub2_Concat = xBlock(struct('source', 'Concat', 'name', 'Concat'), ...
                       struct('num_inputs', 6), ...
                       {xlsub2_Constant3_out1, xlsub2_Constant4_out1, xlsub2_Constant5_out1, xlsub2_Constant6_out1, xlsub2_Constant7_out1, xlsub2_Constant8_out1}, ...
                       {xlsub2_Concat_out1});

% block: SPEAD_packetizer/spead_packet/Concat1
xlsub2_Constant1_out1 = xSignal;
xlsub2_Concat1_out1 = xSignal;
xlsub2_Concat1 = xBlock(struct('source', 'Concat', 'name', 'Concat1'), ...
                        [], ...
                        {xlsub2_Constant1_out1, xlsub2_Assert3_out1}, ...
                        {xlsub2_Concat1_out1});

% block: SPEAD_packetizer/spead_packet/Concat2
xlsub2_Constant13_out1 = xSignal;
xlsub2_Concat2_out1 = xSignal;
xlsub2_Concat2 = xBlock(struct('source', 'Concat', 'name', 'Concat2'), ...
                        [], ...
                        {xlsub2_Constant13_out1, xlsub2_Assert1_out1}, ...
                        {xlsub2_Concat2_out1});

% block: SPEAD_packetizer/spead_packet/Concat3
xlsub2_Constant2_out1 = xSignal;
xlsub2_Concat3_out1 = xSignal;
xlsub2_Concat3 = xBlock(struct('source', 'Concat', 'name', 'Concat3'), ...
                        [], ...
                        {xlsub2_Constant2_out1, xlsub2_Assert2_out1}, ...
                        {xlsub2_Concat3_out1});

% block: SPEAD_packetizer/spead_packet/Concat4
xlsub2_Constant9_out1 = xSignal;
xlsub2_Concat4_out1 = xSignal;
xlsub2_Concat4 = xBlock(struct('source', 'Concat', 'name', 'Concat4'), ...
                        [], ...
                        {xlsub2_Constant9_out1, xlsub2_Assert4_out1}, ...
                        {xlsub2_Concat4_out1});

% block: SPEAD_packetizer/spead_packet/Concat5
xlsub2_Constant10_out1 = xSignal;
xlsub2_Concat5_out1 = xSignal;
xlsub2_Concat5 = xBlock(struct('source', 'Concat', 'name', 'Concat5'), ...
                        [], ...
                        {xlsub2_Constant10_out1, xlsub2_Assert5_out1}, ...
                        {xlsub2_Concat5_out1});

% block: SPEAD_packetizer/spead_packet/Concat6
xlsub2_Constant11_out1 = xSignal;
xlsub2_Concat6_out1 = xSignal;
xlsub2_Concat6 = xBlock(struct('source', 'Concat', 'name', 'Concat6'), ...
                        [], ...
                        {xlsub2_Constant11_out1, xlsub2_Assert7_out1}, ...
                        {xlsub2_Concat6_out1});

% block: SPEAD_packetizer/spead_packet/Concat7
xlsub2_Constant12_out1 = xSignal;
xlsub2_Constant14_out1 = xSignal;
xlsub2_Concat7_out1 = xSignal;
xlsub2_Concat7 = xBlock(struct('source', 'Concat', 'name', 'Concat7'), ...
                        [], ...
                        {xlsub2_Constant12_out1, xlsub2_Constant14_out1}, ...
                        {xlsub2_Concat7_out1});

% block: SPEAD_packetizer/spead_packet/Constant1
xlsub2_Constant1 = xBlock(struct('source', 'Constant', 'name', 'Constant1'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 8388611, ...
                                 'n_bits', 24, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant1_out1});

% block: SPEAD_packetizer/spead_packet/Constant10
xlsub2_Constant10 = xBlock(struct('source', 'Constant', 'name', 'Constant10'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 8388613, ...
                                  'n_bits', 24, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant10_out1});

% block: SPEAD_packetizer/spead_packet/Constant11
xlsub2_Constant11 = xBlock(struct('source', 'Constant', 'name', 'Constant11'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 8388614, ...
                                  'n_bits', 24, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant11_out1});

% block: SPEAD_packetizer/spead_packet/Constant12
xlsub2_Constant12 = xBlock(struct('source', 'Constant', 'name', 'Constant12'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 8388615, ...
                                  'n_bits', 24, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant12_out1});

% block: SPEAD_packetizer/spead_packet/Constant13
xlsub2_Constant13 = xBlock(struct('source', 'Constant', 'name', 'Constant13'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 8388609, ...
                                  'n_bits', 24, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant13_out1});

% block: SPEAD_packetizer/spead_packet/Constant14
xlsub2_Constant14 = xBlock(struct('source', 'Constant', 'name', 'Constant14'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 0, ...
                                  'n_bits', 40, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant14_out1});

% block: SPEAD_packetizer/spead_packet/Constant15
xlsub2_Constant15_out1 = xSignal;
xlsub2_Constant15 = xBlock(struct('source', 'Constant', 'name', 'Constant15'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 1023, ...
                                  'n_bits', 11, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant15_out1});

% block: SPEAD_packetizer/spead_packet/Constant16
xlsub2_Constant16_out1 = xSignal;
xlsub2_Constant16 = xBlock(struct('source', 'Constant', 'name', 'Constant16'), ...
                           struct('arith_type', 'Unsigned', ...
                                  'const', 8, ...
                                  'n_bits', 4, ...
                                  'bin_pt', 0, ...
                                  'explicit_period', 'on'), ...
                           {}, ...
                           {xlsub2_Constant16_out1});

% block: SPEAD_packetizer/spead_packet/Constant2
xlsub2_Constant2 = xBlock(struct('source', 'Constant', 'name', 'Constant2'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 8388610, ...
                                 'n_bits', 24, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant2_out1});

% block: SPEAD_packetizer/spead_packet/Constant3
xlsub2_Constant3 = xBlock(struct('source', 'Constant', 'name', 'Constant3'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 83, ...
                                 'n_bits', 8, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant3_out1});

% block: SPEAD_packetizer/spead_packet/Constant4
xlsub2_Constant4 = xBlock(struct('source', 'Constant', 'name', 'Constant4'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 4, ...
                                 'n_bits', 8, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant4_out1});

% block: SPEAD_packetizer/spead_packet/Constant5
xlsub2_Constant5 = xBlock(struct('source', 'Constant', 'name', 'Constant5'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 3, ...
                                 'n_bits', 8, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant5_out1});

% block: SPEAD_packetizer/spead_packet/Constant6
xlsub2_Constant6 = xBlock(struct('source', 'Constant', 'name', 'Constant6'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 5, ...
                                 'n_bits', 8, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant6_out1});

% block: SPEAD_packetizer/spead_packet/Constant7
xlsub2_Constant7 = xBlock(struct('source', 'Constant', 'name', 'Constant7'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant7_out1});

% block: SPEAD_packetizer/spead_packet/Constant8
xlsub2_Constant8 = xBlock(struct('source', 'Constant', 'name', 'Constant8'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 6, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant8_out1});

% block: SPEAD_packetizer/spead_packet/Constant9
xlsub2_Constant9 = xBlock(struct('source', 'Constant', 'name', 'Constant9'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 8388612, ...
                                 'n_bits', 24, ...
                                 'bin_pt', 0, ...
                                 'explicit_period', 'on'), ...
                          {}, ...
                          {xlsub2_Constant9_out1});

% block: SPEAD_packetizer/spead_packet/Counter1
xlsub2_negedge_out1 = xSignal;
xlsub2_Relational3_out1 = xSignal;
xlsub2_Counter1_out1 = xSignal;
xlsub2_Counter1 = xBlock(struct('source', 'Counter', 'name', 'Counter1'), ...
                         struct('cnt_to', 1023, ...
                                'n_bits', 11, ...
                                'rst', 'on', ...
                                'en', 'on', ...
                                'use_rpm', 'on'), ...
                         {xlsub2_negedge_out1, xlsub2_Relational3_out1}, ...
                         {xlsub2_Counter1_out1});

% block: SPEAD_packetizer/spead_packet/Counter2
xlsub2_posedge1_out1 = xSignal;
xlsub2_Relational2_out1 = xSignal;
xlsub2_Counter2_out1 = xSignal;
xlsub2_Counter2 = xBlock(struct('source', 'Counter', 'name', 'Counter2'), ...
                         struct('cnt_to', 1023, ...
                                'n_bits', 4, ...
                                'rst', 'on', ...
                                'en', 'on', ...
                                'use_rpm', 'on'), ...
                         {xlsub2_posedge1_out1, xlsub2_Relational2_out1}, ...
                         {xlsub2_Counter2_out1});

% block: SPEAD_packetizer/spead_packet/Delay
xlsub2_Delay_out1 = xSignal;
xlsub2_Delay = xBlock(struct('source', 'Delay', 'name', 'Delay'), ...
                      struct('latency', 3, ...
                             'reg_retiming', 'on'), ...
                      {xlsub2_Relational3_out1}, ...
                      {xlsub2_Delay_out1});

% block: SPEAD_packetizer/spead_packet/Delay1
xlsub2_Delay1_out1 = xSignal;
xlsub2_Delay1 = xBlock(struct('source', 'Delay', 'name', 'Delay1'), ...
                       struct('latency', 4, ...
                              'reg_retiming', 'on'), ...
                       {xlsub2_Relational3_out1}, ...
                       {xlsub2_Delay1_out1});

% block: SPEAD_packetizer/spead_packet/Inverter1
xlsub2_Register_out1 = xSignal;
xlsub2_Inverter1_out1 = xSignal;
xlsub2_Inverter1 = xBlock(struct('source', 'Inverter', 'name', 'Inverter1'), ...
                          [], ...
                          {xlsub2_Register_out1}, ...
                          {xlsub2_Inverter1_out1});

% block: SPEAD_packetizer/spead_packet/Inverter5
xlsub2_Inverter5_out1 = xSignal;
xlsub2_Inverter5 = xBlock(struct('source', 'Inverter', 'name', 'Inverter5'), ...
                          [], ...
                          {xlsub2_Relational2_out1}, ...
                          {xlsub2_Inverter5_out1});

% block: SPEAD_packetizer/spead_packet/Inverter6
xlsub2_Inverter6_out1 = xSignal;
xlsub2_Inverter6 = xBlock(struct('source', 'Inverter', 'name', 'Inverter6'), ...
                          [], ...
                          {xlsub2_Relational3_out1}, ...
                          {xlsub2_Inverter6_out1});

% block: SPEAD_packetizer/spead_packet/Logical2
xlsub2_Logical2_out1 = xSignal;
xlsub2_Logical2 = xBlock(struct('source', 'Logical', 'name', 'Logical2'), ...
                         struct('inputs', 4, ...
                                'n_bits', 8, ...
                                'bin_pt', 2), ...
                         {xlsub2_Inverter5_out1, xlsub2_Inverter6_out1, xlsub2_Inverter1_out1, xlsub2_Assert8_out1}, ...
                         {xlsub2_Logical2_out1});

% block: SPEAD_packetizer/spead_packet/Logical3
xlsub2_Logical3 = xBlock(struct('source', 'Logical', 'name', 'Logical3'), ...
                         struct('logical_function', 'OR', ...
                                'n_bits', 8, ...
                                'bin_pt', 2), ...
                         {xlsub2_Relational2_out1, xlsub2_Delay1_out1}, ...
                         {xlsub2_data_valid1});

% block: SPEAD_packetizer/spead_packet/Mux2
xlsub2_Mux2 = xBlock(struct('source', 'Mux', 'name', 'Mux2'), ...
                     struct('inputs', '9', ...
                            'arith_type', 'Signed  (2''s comp)', ...
                            'n_bits', 8, ...
                            'bin_pt', 2), ...
                     {xlsub2_Counter2_out1, xlsub2_Concat_out1, xlsub2_Concat2_out1, xlsub2_Concat3_out1, xlsub2_Concat1_out1, xlsub2_Concat4_out1, xlsub2_Concat5_out1, xlsub2_Concat6_out1, xlsub2_Concat7_out1, xlsub2_Assert6_out1}, ...
                     {xlsub2_data_out});

% block: SPEAD_packetizer/spead_packet/Register
xlsub2_negedge2_out1 = xSignal;
xlsub2_Register = xBlock(struct('source', 'Register', 'name', 'Register'), ...
                         struct('rst', 'on', ...
                                'en', 'on'), ...
                         {xlsub2_posedge1_out1, xlsub2_negedge2_out1, xlsub2_posedge1_out1}, ...
                         {xlsub2_Register_out1});

% block: SPEAD_packetizer/spead_packet/Relational2
xlsub2_Relational2 = xBlock(struct('source', 'Relational', 'name', 'Relational2'), ...
                            struct('mode', 'a<b', ...
                                   'latency', 0), ...
                            {xlsub2_Counter2_out1, xlsub2_Constant16_out1}, ...
                            {xlsub2_Relational2_out1});

% block: SPEAD_packetizer/spead_packet/Relational3
xlsub2_Relational3 = xBlock(struct('source', 'Relational', 'name', 'Relational3'), ...
                            struct('mode', 'a<=b', ...
                                   'latency', 0), ...
                            {xlsub2_Counter1_out1, xlsub2_Constant15_out1}, ...
                            {xlsub2_Relational3_out1});

% block: SPEAD_packetizer/spead_packet/negedge
xlsub2_negedge = xBlock(struct('source', 'casper_library_misc/negedge', 'name', 'negedge'), ...
                        [], ...
                        {xlsub2_Relational2_out1}, ...
                        {xlsub2_negedge_out1});

% block: SPEAD_packetizer/spead_packet/negedge1
xlsub2_negedge1 = xBlock(struct('source', 'casper_library_misc/negedge', 'name', 'negedge1'), ...
                         [], ...
                         {xlsub2_Delay_out1}, ...
                         {xlsub2_eof});

% block: SPEAD_packetizer/spead_packet/negedge2
xlsub2_negedge2 = xBlock(struct('source', 'casper_library_misc/negedge', 'name', 'negedge2'), ...
                         [], ...
                         {xlsub2_Relational3_out1}, ...
                         {xlsub2_negedge2_out1});

% block: SPEAD_packetizer/spead_packet/posedge1
xlsub2_posedge1 = xBlock(struct('source', 'casper_library_misc/posedge', 'name', 'posedge1'), ...
                         [], ...
                         {xlsub2_Logical2_out1}, ...
                         {xlsub2_posedge1_out1});

% extra outport assignment
xlsub2_ack_out.assign(xlsub2_Relational3_out1);


end

