#ifndef __psrfits_subband_cmd__
#define __psrfits_subband_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -dm: Dispersion measure to use for the subband de-dispersion */
  char dmP;
  double dm;
  int dmC;
  /***** -nsub: Number of output frequency subbands */
  char nsubP;
  int nsub;
  int nsubC;
  /***** -dstime: Power-of-2 number of samples to average in time */
  char dstimeP;
  int dstime;
  int dstimeC;
  /***** -startfile: Starting file number of sequence */
  char startfileP;
  int startfile;
  int startfileC;
  /***** -numfiles: Number of files to process */
  char numfilesP;
  int numfiles;
  int numfilesC;
  /***** -filetime: Desired length of the resulting files in sec */
  char filetimeP;
  float filetime;
  int filetimeC;
  /***** -filelen: Desired length of the resulting files in GB */
  char filelenP;
  float filelen;
  int filelenC;
  /***** -bytes: Make the raw data unsigned chars instead of signed shorts */
  char bytesP;
  /***** -onlyI: Only output total intensity data */
  char inlyIP;
  /***** -weights: Filename containing ASCII list of channels and weights to use */
  char wgtsfileP;
  char* wgtsfile;
  int wgtsfileC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

